name: Manual
on:
  workflow_dispatch:                            #この指定は手動実行ということ
    inputs:                                     #入力させる
      greeting:                                 #入力された値を入れる変数名()
        type: string                            #変数のデータ型 stringなので文字列
        default: Hello                          #変数のデフォルト値
        required: true                          #入力パラメータの必須フラグ。trueなら必須,falseなら必須じゃない
        descriptions: A cheerful Word           #descriptions なので概要

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"      #入力させる変数は←みたいな指定で参照するらしい。これはgithub actions独自の記載らしい